### ISSUE TITLE
GNSS metadata block

### ISSUE THREAD

**Issue by linguini1** [CarletonURocketry/packager#16]
An implementation for the GNSS metadata block needs to be added to the packet types. The implementation should follow the style of previous implementations.

See `/docs/radio_packet_format.pdf` section `3.3.6` for more information.

**Comment by AngusJull** [comment]
@isharghura This might be a good one to start with, though I see you assigned and unassigned yourself. If you do want to do this one (just to get used to things), feel free to ask me any questions you have and I'll try and answer them

**Comment by AngusJull** [comment]
We're choosing not to include the GNSS metadata in logging/radio transmission right now. Might revisit the issue next year.
