### ISSUE TITLE
Change type unions for packet types into raw byte arrays + helpers to extract certain parts.

### ISSUE THREAD

**Issue by linguini1** [CarletonURocketry/packager#22]
Following some research regarding bit-fields within C structs, it turns out that it's not possible to guarantee the order of the fields once compiled. This means that we cannot use our current type-union between byte arrays and structs in order to encode packet data, or our packets will not follow the spec when sent over radio.

[C bit-fields standard](https://stackoverflow.com/questions/19376426/order-of-fields-when-using-a-bit-field-in-c)

To resolve this issue, we will need to do the following:

Typedef packet types as being pure byte arrays:

```c
typedef uint8_t PacketHeader[4];
```

Provide functions or macros for accessing parts of the byte array using masks:
```c
uint8_t inline get_length(PacketHeader *p){
    return *p & 0x0FF0; // This is a made up mask that doesn't follow the real packet spec
}
```

**Comment by linguini1** [comment]
[Another article](https://stackoverflow.com/questions/16803397/can-endianness-refer-to-bits-order-in-a-byte#:~:text=Bit%20order%20is%20very%20similar,C%20bus%3B%20one%20after%20another)

**Comment by AngusJull** [comment]
Branch is unions-to-raw

**Comment by AngusJull** [comment]
This webpage lists two good options for using inline: https://www.greenend.org.uk/rjk/tech/inline.html - the first is that we make a definition in packet_types.h and use `static inline` function definitions. This looks the most like a macro, but there's a chance the compiler will compile and use the function like normal and waste some space. Alternatively, we can use `extern inline` definitions in the header, and provide a single regular definition in packet_types.c - this only works with GNU but means that if the function isn't used as inline, it will use the regular definition. 

If we're confident we're sticking with GNU C and not using an older C compiler like C99, then we might want to use the second method

**Comment by linguini1** [comment]
> Alternatively, we can use extern inline definitions in the header, and provide a single regular definition in packet_types.c - this only works with GNU but means that if the function isn't used as inline, it will use the regular definition.

Let's do the second option! We're using the gnu11 standard.
