### ISSUE TITLE
Revert back to structs

### ISSUE THREAD

**Issue by linguini1** [CarletonURocketry/packager#54]
Since we now have a packet encoding that doesn't require strange bit-fields, we should revert back to normal structs.

Ex:
Instead of:
```c
typedef struct {
    uint8_t bytes[8];
} PressureDB;
```
We should have:
```c
typedef struct {
    uint32_t mission_time;
    uint32_t pressure;
} PressureDB;
```

**Comment by JowiAoun** [comment]
Working on this issue, accidentally marked as complete
