### ISSUE TITLE
Set up unit testing

### ISSUE THREAD

**Issue by linguini1** [CarletonURocketry/packager#7]
There should be some unit testing going on for our library functions. It will not have to be anything fancy; using `asserts` should be enough for the most part.

I am envisioning tests being in the directory structure like so:

```
C:.
├───.github
│   └───workflows
├───docs
├───nto-aarch64-o.le
├───nto-x86_64-o
├───src
│   └───include
└─tests
   ├───bin
   │   ├───packet_header_tests.exe
   │   ├───packet_data_tests.exe
   │   └───....
   └───packet_header_tests
       ├───packet_header_test.c
       └───...
```

The tests directory will contain sub directories for each group of unit tests (packet header tests, packet data tests, etc.). The Makefile within the tests directory should hook into QNX's build system (see other Makefiles in the `nto-*` directories) to create a bin directory full of all the unit test binaries. These test binaries should be executed via a `make test` command in the project's root Makefile.

This is just an idea and could be expanded on.

**Comment by linguini1** [comment]
Unfortunately, [QNX cannot be run in a Docker image](https://forums.docker.com/t/docker-for-rtos/283). However, QNX libraries can be run on Linux since they're POSIX compliant. The tests should be built for an x86 Linux machine so they can be run in Docker.

You can read the [QNX docs for Makefile conventions](https://www.qnx.com/developers/docs/7.1/#com.qnx.doc.neutrino.prog/topic/make_convent_Directory_levels.html) in order to get an idea of how to set that up. Keep in mind that we only want the _tests_ compiled for Linux x86, not the whole project (for now). It would be good to have that option.

If you are stuck on building for Linux, please ask me and I can try to help and/or bother our Blackberry contact more.

**Comment by ryangchung** [comment]
Hi, could I pick this up?

Thanks!

**Comment by linguini1** [comment]
> Hi, could I pick this up?
> 
> Thanks!

Yes! Feel free to assign yourself to any issue you'd like to work on and get started on a branch!
